language: cpp

sudo: required
dist: trusty

matrix:
    include:
    - os: linux
      compiler: gcc
      env: GCC_VERSION=8
        CC=gcc-8
        CXX=g++-8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gcc-8
  - sudo apt-get install -y g++-8

before_script:
  - ulimit -c unlimited -S       # enable core dumps

script:
  - mkdir build && cd build
  - cmake .. && make